#!/bin/bash
/usr/bin/generate-certs | tee /var/log/generate-certs.log
exec /usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2376 \
    --containerd=/run/containerd/containerd.sock \
    --tlsverify --tlscacert=/etc/docker/server/ca.pem \
    --tlscert=/etc/docker/server/cert.pem \
    --tlskey=/etc/docker/server/key.pem